name: 'Chromatic Publish'

on:
  pull_request:
    branches:
      - develop
    paths:
      - 'packages/design-system/**'

permissions: write-all

jobs:
  storybook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup pnpm and Node.js
        uses: ./.github/actions/pnpm-setup-node

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Storybook for Design System
        run: pnpm --filter @confeti/design-system run build-storybook

      - name: Publish to Chromatic
        id: chromatic
        uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.AUTO_SYNC_CHROMATIC }}
          token: ${{ secrets.SECRET_KEY }}
          onlyChanged: true
          autoAcceptChanges: true
          storybookBaseDir: packages/design-system

      - name: Comment PR
        if: github.event_name == 'pull_request'
        uses: thollander/actions-comment-pull-request@v3
        env:
          GITHUB_TOKEN: ${{ secrets.SECRET_KEY }}
        with:
          comment-tag: ${{github.event.number}}-storybook
          message: 'üè¥‚Äç‚ò†Ô∏è Storybook ÌôïÏù∏: üîó ${{ steps.chromatic.outputs.storybookUrl }}'
          mode: upsert
